<h6>ver. Mar-2024</h6>

<h3>Python for Sqlite3 </h3>

<h4>1. Employee class for OOP implementation.</h4>

In [2]:
class Employee:
    def __init__(self, firstName, lastName, pay):
        self.firstName = firstName
        self.lastName = lastName
        self.pay = pay

    def email(self):
        return '{].{}@email.com'.format(self.firstName, self.lastName)

    def fullName(self):
        return '{} {}'.format(self.firstName, self.lastName)

    def __repr__(self):
        return "Employee('{}', '{}', {})".format(self.firstName, self.lastName, self.pay)


<h4>2. CRUD Database by Python.</h4>

In [ ]:
import sqlite3
import Employee


''' Create a connection instance '''
''' Database on memory is used for testing in development phase. '''
conn = sqlite3.connect(':memory:')
    
''' Database on file:   if the file does not exist --> create the database file && connect
                        if exist, connect '''
# conn = sqlite3.connect('employee.db')

''' create a cursor object '''
c = conn.cursor()

''' create employee table in the Database '''
c.execute("""CREATE TABLE employees (
            firstName text,
            lastName text,
            pay integer
            )""")

''' all inner methods must be declared beofore it is used '''
def insert_emp(emp):
    with conn:
        c.execute("INSERT INTO employees VALUES (:firstName, :lastName, :pay)", {'firstName': emp.firstName, 'lastName': emp.lastName, 'pay': emp.pay})

def get_emps_by_name(lastName):
    c.execute("SELECT * FROM employees WHERE lastName = :lastName", {'lastName': lastName})
    return c.fetchall()

def update_pay(emp, pay):
    with conn:
        c.execute("""UPDATE employees SET pay = :pay 
                    WHERE firstName = :firstName AND lastName = :lastName""",
                    {'firstName': emp.firstName, 'lastName': emp.lastName, 'pay':pay})

def remove_emp(emp):
    with conn:
        c.execute("DELETE FROM employees  WHERE firstName = :firstName AND lastName = :lastName",
                    {'firstName': emp.firstName, 'lastName': emp.lastName})

''' insert an employee data by SQL '''
c.execute("INSERT INTO employees VALUES ('Mary', 'Schafer', 70000)")
c.execute("INSERT INTO employees VALUES ('Samuel', 'Schafer', 70000)")

''' create an Employee object for OOP implementaion '''
employee1 = Employee('John', 'Doe', 80000)
employee2 = Employee('Jane', 'Doe', 90000)

''' insert data on ?, ? statement '''
# c.execute("INSERT INTO employees VALUES (?, ?, ?)", (employee1.firstName, employee1.lastName, employee1.pay))

''' insert data on dictionary statement '''
# c.execute("INSERT INTO employees VALUES (:firstName, :lastName, :pay)", {'firstName': employee2.firstName, 'lastName': employee2.lastName, 'pay': employee2.pay})

insert_emp(employee1)
insert_emp(employee2)
# print(employee1)

emps = get_emps_by_name('Doe')
print(emps)

update_pay(employee2, 95000)
remove_emp(employee1)
emps = get_emps_by_name('Doe')
print(emps)

''' commit to updata database '''
conn.commit()

''' retrieve data by SQL statement '''
# c.execute("SELECT * FROM employees WHERE lastName = 'Schafer'")
# c.execute("SELECT * FROM employees WHERE lastName = ?", ('Schafer',))
# print(c.fetchall())

# c.execute("SELECT * FROM employees WHERE lastName = :lastName", {'lastName': 'Doe'})
# print(c.fetchall())

# c.execute("SELECT * FROM employees WHERE lastName = 'Schafer'")
# print(c.fetchall())

''' close database connection '''
conn.close()